apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
    interval: 5m
    successCondition: result[0] >= 0.95
    failureLimit: 3
    provider:
      prometheus:
        address: http://prometheus.linkerd-viz.svc.cluster.local:9090
        timeout: 40
        query: |
          sum(irate(response_total{direction = "inbound", app="{{args.app-name}}", classification="success"}[1m]))
          /
          sum(irate(response_total{direction = "inbound",app="{{args.app-name}}"}[1m]))

