kind: Service
apiVersion: v1
metadata:
  name:  canary-demo-web
  annotations:
        linkerd.io/inject: enabled
spec:
  selector:
    app:  canary-demo-web
  type:  ClusterIP
  ports:
  - name:  http
    port:  80
    targetPort:  3000